region          = "us-west-2"
ami_id          = "ami-05134c8ef96964280"
instance_type   = "t2.micro"
discord_bot_application_id = ""
discord_bot_token  = ""
discord_server_id = ""
discord_user_id = ""
discord_invite_link = "https://discord.gg/<your_invite_id>"
yt_credential = "access_token=...; expiry_date=..."
allowed_ip = "1.1.1.1"
public_key_path = "~/.ssh/<your-pub-file>"